dataset:
  type: 'Senz'    # 数据集类型 决定Dataset类
  name: 'Senz'    # 数据集名称
  root: 'd:\Python\dataset\Senz3d\'    # 数据集根目录路径
  split_type: 'train'            # 使用的数据集划分部分
  to_tensor: True    # 是否转为tensor
  # params: False                     # 数据集参数 应该与Dataset类的关键词参数对应
  
  params:
    to_yuv: False    # 是否转为YUV格式
    filter_type: 'none'    # 过滤器类型 'none', 'gaussian', 'median', 'bilateral'
    