dataset:
  type: 'RHD'    # 数据集类型 决定Dataset类
  name: 'RHD'    # 数据集名称
  root: 'd:\Python\dataset\RHD\'    # 数据集根目录路径
  split_type: 'test'            # 使用的数据集划分部分
  to_tensor: True    # 是否转为tensor
  # params: False                     # 数据集参数 应该与Dataset类的关键词参数对应
  params:
    use_modified_depth: True    # 是否使用修改过的RHD深度图
    to_yuv: False    # 是否转为YUV格式
    