segmentation:    # 分割参数
  type: 'ResNet'    # 分割算法类型
  model_path: '.\ResNet\checkpoint\checkpoint.ckpt'    # 模型路径
  params: 
    predict_width: 256   # 预测输入图像宽度
    predict_height: 256   # 预测输入图像高度
    