segmentation:    # 分割参数
  type: 'RDF'    # 分割算法类型
  params:
    n_estimators: 300    # 决策树数量
    max_depth: 20    # 决策树最大深度
    min_samples_split: 2    # 划分节点最小样本数
    min_samples_leaf: 1    # 叶子节点最小样本数
    # random_state: 0    # 随机种子