segmentation:    # 分割参数
  type: 'RDF'    # 分割算法类型
  params:
    n_estimators: 300    # 决策树数量
    max_depth: 20    # 决策树最大深度
    min_samples_split: 2    # 划分节点最小样本数
    min_samples_leaf: 1    # 叶子节点最小样本数
    # random_state: 0    # 随机种子
    pixel_count: 2000    # 每张图片采样的像素数量
    threshold_split: 50    # 深度特征的比较阈值的分割点数目
    threshold_min: -1.0    # 深度特征的比较阈值的最小值
    threshold_max: 1.0    # 深度特征的比较阈值的最大值
    offset_min: 0        # 偏移向量长度最小值
    offset_max: 10.0        # 偏移向量长度最小值