dataset:
  type: 'RHD'    # 数据集类型 决定Dataset类
  name: 'RHD'    # 数据集名称
  root: 'd:\Python\dataset\RHD\'    # 数据集根目录路径
  split_type: 'train'            # 使用的数据集划分部分
  params: False                     # 数据集参数 应该与Dataset类的关键词参数对应
  # params:
    # to_tensor: False    # 是否转为tensor

segmentation:    # 分割参数
  type: 'RDF'    # 分割算法类型
  params:
    n_estimators: 300    # 决策树数量
    max_depth: 20    # 决策树最大深度
    min_samples_split: 2    # 划分节点最小样本数
    min_samples_leaf: 1    # 叶子节点最小样本数
    # random_state: 0    # 随机种子