dataset:
  type: 'RHD'    # 数据集类型 决定Dataset类
  name: 'RHD'    # 数据集名称
  root: 'd:\Python\dataset\RHD\'    # 数据集根目录路径
  split_type: 'train'            # 使用的数据集划分部分
  # params: False                     # 数据集参数 应该与Dataset类的关键词参数对应
  params:
    # to_tensor: False    # 是否转为tensor
    use_modified_depth: True    # 是否使用修改过的RHD深度图
    
# dataset:
#   type: 'IsoGD'    # 数据集类型 决定Dataset类
#   name: 'ChaLearn-IsoGD'    # 数据集名称
#   root: 'd:\Python\dataset\ChaLearn-IsoGD\'    # 数据集根目录路径
#   split_type: 'train'            # 使用的数据集划分部分
#   # params: False                     # 数据集参数 应该与Dataset类的关键词参数对应
#   params:
#     to_tensor: True    # 是否转为tensor
#     buffer_size: 0    # 数据缓存大小

segmentation:    # 分割参数
  type: 'RDF'    # 分割算法类型
  params:
    n_estimators: 300    # 决策树数量
    max_depth: 20    # 决策树最大深度
    min_samples_split: 2    # 划分节点最小样本数
    min_samples_leaf: 1    # 叶子节点最小样本数
    # random_state: 0    # 随机种子
    pixel_count: 2000    # 每张图片采样的像素数量
    threshold_split: 50    # 深度特征的比较阈值的分割点数目
    threshold_min: -1.0    # 深度特征的比较阈值的最小值
    threshold_max: 1.0    # 深度特征的比较阈值的最大值
    offset_min: 0        # 偏移向量长度最小值
    offset_max: 10.0        # 偏移向量长度最小值

evaluation:    # 评估参数
  depth_max_diff: 4.0    # 最大深度差值dM
  depth_match_threshold: 1.0    # 判断两者匹配的深度差值阈值