tracking:
  type: '3DSC'  # 追踪器类型
  params:
    contour_threshold: 0.1  # 应用sobel算子后被认为是轮廓像素的阈值
    contour_max_points: 80  # 轮廓的最大点数
    coutour_simplify_eplision: 0.0001  # 轮廓简化的精度 （与轮廓长度相乘）
    use_naive_simplify: True  # 是否使用简单的轮廓简化算法